
CREATE TABLE AUTHORITY_HOLDER(
    ID INT(2) AUTO_INCREMENT PRIMARY KEY,
    PARAM  CHAR(10)   NOT NULL,

    FOREIGN KEY  (ID)  REFERENCES  ADMIN_STAFF(ID)  ON DELETE CASCADE,
    FOREIGN KEY  (PARAM)  REFERENCES  ADMIN_STAFF(AUTHORITY) 
);