
//権限認証クエリ
//セッションユーザ変数の名前と権限を認証
SELECT PARAM  FROM AUTHORITY_HOLDER WHERE PARAM IN (
    SELECT AUTHORITY FROM ADMIN_STAFF  WHERE AUTHORITY = AUTHORITY_HOLDER.PARAM  AND ID =1
);

SELECT * FROM SUBJECT_SCORE;


/*生徒情報に格納するクエリ*/

INSERT INTO STUDENT_INFORMATION(ID ,STUDENT_NAME,POST_NUMBER, ADDRESS,TELEPHONE_NUMBER,MAIL_ADDRESS) VALUES(NULL,'テストデータ7','XXX-XXXX','XX県XX市','XXX-XXXX-XXXX','XXXX@gmail.com') 
,(NULL,'テストデータ17','XXX-XXXX','XX県XX市','XXX-XXXX-XXXX','XXXX@gmail.com'),
(NULL,'テストデータ18','XXX-XXXX','XX県XX市','XXX-XXXX-XXXX','XXXX@gmail.com') ,
(NULL,'テストデータ19','XXX-XXXX','XX県XX市','XXX-XXXX-XXXX','XXXX@gmail.com'),
(NULL,'テストデータ20','XXX-XXXX','XX県XX市','XXX-XXXX-XXXX','XXXX@gmail.com') ,
(NULL,'テストデータ21','XXX-XXXX','XX県XX市','XXX-XXXX-XXXX','XXXX@gmail.com');

UPDATE  STUDENT_INFORMATION SET attended_time = RAND()*50+50 ,SCIENCE_SCORE =  RAND()*50+30  ,TECHNOLOGY_SCORE = RAND()*50+40 ,ENGINEERING_SCORE  = RAND()*50+30, MATH_SCORE  = RAND()*50+30 WHERE ID  > 2;


UPDATE  STUDENT_INFORMATION SET attended_time = RAND()*182;

SELECT * FROM ALERT_SENDER  
SELECT * FROM CONTACT_ADDRESS   
SELECT * FROM SUBJECT_SCORE




 SELECT * FROM adminuser \n
INTO OUTFILE 'C:/Users/cl05/Desktop/test1.csv' \n
CHARACTER SET sjis\n
     FIELDS TERMINATED BY ','\n
    OPTIONALLY ENCLOSED BY '\"'\n
    ESCAPED BY ''\n
	LINES TERMINATED BY '\n';