CREATE  TABLE DROPOUT_STUDENT(
    ID INT  AUTO_INCREMENT PRIMARY KEY,
    STUDENT_NAME  CHAR(10) ,
    REMAKS    VARCHAR(30),
    FOREIGN KEY (ID)   REFERENCES STUDENT_INFORMATION(ID) ON DELETE CASCADE    
);


