
CREATE TABLE Examination_status(

    ID  INT AUTO_INCREMENT PRIMARY KEY ,
    SCIENCE_SCORE_RESULT BOOLEAN  DEFAULT FALSE ,
    TECHNOLOGY_SCORE_RESULT  BOOLEAN  DEFAULT  FALSE,
    ENGINEERING_SCORE_RESULT BOOLEAN  DEFAULT  FALSE,
    MATH_SCORE_RESULT  BOOLEAN   DEFAULT FALSE,
    FOREIGN KEY  (ID) REFERENCES STUDENT_INFORMATION (ID)  ON DELETE CASCADE

);

