
CREATE TABLE ADMIN_STAFF (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USERNAME  VARCHAR(8)   NOT NULL,
    PASSWORD  VARCHAR(8)   NOT NULL,
    AUTHORITY CHAR(10)     NOT NULL,

    INDEX(AUTHORITY),
    INDEX(PASSWORD)
);