
    CREATE TABLE STUDENT_INFORMATION(
        ID INT  AUTO_INCREMENT  PRIMARY KEY,
        STUDENT_NAME CHAR(10)  NOT NULL,
        POST_NUMBER  CHAR(8) NOT NULL,
        ADDRESS VARCHAR(30) NOT NULL,
        TELEPHONE_NUMBER  CHAR(13)    NOT NULL,
        MAIL_ADDRESS      VARCHAR(50)  NOT NULL,
        Enrollment_status BOOLEAN   DEFAULT TRUE ,
        ATTENDED_TIME     INT DEFAULT  0,
        SCIENCE_SCORE     INT DEFAULT  0,
        TECHNOLOGY_SCORE  INT DEFAULT  0,
        ENGINEERING_SCORE INT DEFAULT  0, 
        MATH_SCORE        INT DEFAULT  0,
        INDEX(Enrollment_status)
    );





-- ALTER TABLE STUDENT_INFORMATION ADD COLUMN  ATTENDED_TIME INT DEFAULT 0   AFTER  Enrollment_status;

